spring.application.name=ApiGateway
server.port=8080

# Connect to Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Spring Cloud 2024/2025 WebFlux Routing Rules
spring.cloud.gateway.server.webflux.routes[0].id=restaurant-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://restaurantservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/restaurants/**

spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://orderservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**
