spring.application.name=EurekaServer
server.port=8761

# Tell this app that it IS the server, not a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost